# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_day', models.IntegerField()),
                ('payment_due_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_total', models.IntegerField()),
                ('aliquot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('way_to_pay', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Deposito Bancario'), ('3', 'Transferencia'), ('4', 'Cheque')], max_length=10)),
                ('number', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=1000)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_prefix', models.CharField(choices=[('1', 'V'), ('2', 'E'), ('3', 'J'), ('4', 'G')], max_length=10)),
                ('id_card', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('local_phone_area', models.CharField(max_length=25)),
                ('local_phone', models.CharField(max_length=50)),
                ('mobile_phone_area', models.CharField(max_length=25)),
                ('mobile_phone', models.CharField(max_length=50)),
                ('work_phone_area', models.CharField(max_length=25)),
                ('work_phone', models.CharField(max_length=50)),
                ('billing_address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Property'),
        ),
        migrations.AddField(
            model_name='contract',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Local'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Tenant'),
        ),
    ]
